spring:
  application:
    name: order-service #注意：这里和IOrderService的注解上起的名字保持一致

server:
  port: 8083


management:
  endpoints:
    web:
      exposure:
        include: refresh #允许actuator的一个请求，用来刷新配置。url: http://localhost:8082/actuator/refresh