spring:
  cloud:
    gateway:
      routes:
        - id: neo_route
          uri: http://www.ityouknow.com
          predicates:
            - Path=/cartoon.html

management:
  endpoints:
    web:
      exposure:
        include: gateway

